data_root_dir: /pub0/qasim/biology/data
run_dir: /pub0/qasim/biology/uma_runs
account: ocp
qos: ocp
mode: LOCAL
device: CUDA
ranks_per_node: 1
dataloader_workers: 0
debug: False
mem_gb: 0
cpus_per_task: 24
