data_root_dir: /pub0/qasim/biology/train_4M
run_dir: /pub0/qasim/biology/uma_runs
account: ocp
qos: ocp
mode: SLURM
device: CUDA
ranks_per_node: 8
dataloader_workers: 8
debug: False
mem_gb: 0
cpus_per_task: 24
